/*Generated by localizable2appstrings automatically. Don't change the content of this file!*/

import SiFUtilities
import Foundation

struct Text {
    static let newTextHere = "new_text_here".localized
    static let welcomeMessage = "welcome_message".localized
    static let welcomeTitle = "welcome_title".localized
}