/*Generated by localizable2appstrings automatically. Don't change the content of this file!*/

import SiFUtilities
import Foundation

public struct Text {
    public static var newTextHere: String { return "new_text_here".localized }
    public static var welcomeMessage: String { return "welcome_message".localized }
    public static var welcomeTitle: String { return "welcome_title".localized }
}